### PR TITLE
Reinitialize autocomplete to add limit value

### LINKED ISSUE #780: Autocomplete is not working
In production.

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #780 

Fixes autocomplete on production. Tested with tunneled connection to the production solr instance. I'm not sure why exactly this works, but I will push this upstream to Blacklight and see if others might have insight into it.

### CODE REVIEW

File: app/assets/javascripts/modules/autocomplete.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+      }
+    });
+    terms.initialize();
+    $el.typeahead({
+      hint: true,
+      highlight: true,
+      minLength: 2
+    }, {
+      name: 'terms',
+      limit: 10,
```
Comment (eliotjordan) [inline app/assets/javascripts/modules/autocomplete.js]: Key here is the value 10, which is twice the number of returned results. Any less and the displayed results are progressively truncated to zero.

Comment (jrgriffiniii) [reply app/assets/javascripts/modules/autocomplete.js]: I'm not certain of the status for our staging infrastructure at this moment, so I'm just trying to run this locally.
