### PR TITLE
Redirect to 404 when document is not downloadable

### LINKED ISSUE #556: [Pulmap/production] ActionView::Template::Error: undefined method `first' for nil:NilClass
## Backtrace

    line 13 of [PROJECT_ROOT]/app/views/catalog/_downloads_primary.html.erb: _app_views_catalog__downloads_primary_html_erb__2603021758117852692_33978740
    line 10 of [PROJECT_ROOT]/app/views/catalog/downloads.html.erb: _app_views_catalog_downloads_html_erb___4427280619804354529_34106400

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/37658102)

### PR DESCRIPTION
**Pull request by eliotjordan**
Redirect to 404 page when attempting to access downloads route on non-downloadable or non-Princeton documents.
 
Closes #556

### CODE REVIEW

File: spec/controllers/catalog_controller_spec.rb [hunk 1]
```diff
@@ -10,10 +10,26 @@
...
+    context 'with a downloadable Princeton item' do
+      it 'renders dowload page' do
+        get :downloads, params: { id: 'princeton-m613n013z' }
+        expect(response).to have_http_status(200)
+        expect(assigns(:document)).not_to be_nil
+      end
+    end
+
+    context 'with a downloadable non-Princeton item' do
+      it 'renders dowload page' do
```
Comment (tampakis) [inline spec/controllers/catalog_controller_spec.rb]: Looks good, just update the spec text.
