### PR TITLE
Rescue ActiveSupport::MessageVerifier::InvalidSignature exception

### LINKED ISSUE #949: [Pulmap/production] ActiveSupport::MessageVerifier::InvalidSignature: ActiveSupport::MessageVerifier::InvalidSignature
This error started happening on June 5th. 

Should we handle this exception so that we don't add noise to Honeybadger? 

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/79805504)

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #949

### CODE REVIEW

**Review by hackartisan — APPROVED** [review]
Looks good but looks like it needs to be rebased.

**Comment by eliotjordan** [comment]
@hackartisan Rebased and added new method.

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -9,12 +9,20 @@ class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
 
   rescue_from Blacklight::Exceptions::RecordNotFound do
```
Comment (hackartisan) [inline app/controllers/application_controller.rb:11]: could this be `rescue_from ActiveSupport::etc, Blacklight::etc`? Might need to be split onto 2 lines because the exceptions are long but still might be a bit tighter.

Comment (eliotjordan) [reply app/controllers/application_controller.rb]: @hackartisan I just pushed up a changes along this line, but hopefully easier on the eyes and simpler to expand in the future.

**Review by hackartisan — APPROVED** [review]
Thanks!
